runtime: python27
api_version: 1
threadsafe: true
skip_files:
- .git/
- .gitingore
- README.md

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /index(.*)
  static_files: index.html
  upload: index.html

- url: /assets/(.*)
  static_files: assets/\1
  upload: assets/(.*)

- url: /css/(.*)
  static_files: css/\1
  upload: css/(.*)

- url: /img/(.*)
  static_files: img/\1
  upload: img/(.*)

- url: /js/(.*)
  static_files: js/\1
  upload: js/(.*)

